# Definición de campos y tipos según Contract Database

# Asignaciones múltiples por nombre interno
tabla_por_campo = {
    'contract_tree_information': {
        'contract_code', 'etp_year', 'planting_year', 'harvest_year', 'region',
        'land_location', 'latitude', 'longitude', 'trees_contract', 'planted',
        'planting_obligation', 'contract_amendment', 'species', 'strain'
    },
    'contract_farmer_information': {
        'contract_code', 'representative', 'farmer_number', 'contract_name',
        'phone', 'status', 'email', 'address', 'shipping_address'
    },
    'contract_allocation': {
        'contract_code', 'usa_allocation_pct', 'usa_trees_contracted', 'usa_trees_planted',
        'canada_allocation_pct', 'canada_trees_contracted', 'canada_2017_allocation_pct',
        'canada_2017_trees', 'total_can_allocation'
    },
    'contract_replacements': {
        'contract_code', 'pct_replaced', 'total_replacements', 'replace_25', 'replace_24',
        'replace_23', 'replace_22', 'replace_21', 'replace_20', 'replace_19',
        'replace_18', 'replace_17', 'replace_16'
    }
}


field_schema = {'Contract Code': ('contract_code', 'TEXT',
                                  ['contract_tree_information', 'contract_farmer_information', 'contract_allocation',
                                   'contract_replacements']),
                'ETP Year': ('etp_year', 'SMALLINT', ['contract_tree_information']),
                'Planting Year': ('planting_year', 'SMALLINT', ['contract_tree_information']),
                'Harvest Year (10 year)': ('harvest_year', 'SMALLINT', ['contract_tree_information']),
                'Representative': ('representative', 'TEXT', ['contract_farmer_information']),
                'Farmer#': ('farmer_number', 'TEXT', ['contract_farmer_information']),
                'Contract Name': ('contract_name', 'TEXT', ['contract_farmer_information']),
                'Phone': ('phone', 'TEXT', ['contract_farmer_information']),
                'Status': ('status', 'TEXT', ['contract_farmer_information']),
                'Email': ('email', 'TEXT', ['contract_farmer_information']),
                'Address': ('address', 'TEXT', ['contract_farmer_information']),
                'Shipping Address': ('shipping_address', 'TEXT', ['contract_farmer_information']),
                'Region': ('region', 'TEXT', ['contract_tree_information']),
                'Land Location (GPS)': ('land_location', 'TEXT', ['contract_tree_information']),
                'Latitude': ('latitude', 'DOUBLE PRECISION', ['contract_tree_information']),
                'Longitude': ('longitude', 'DOUBLE PRECISION', ['contract_tree_information']),
                'Column1': ('column1', 'TEXT', None), 'Column2': ('column2', 'TEXT', None),
                'Column3': ('column3', 'TEXT', None),
                '#TreesContract': ('trees_contract', 'SMALLINT', ['contract_tree_information']),
                '#Planted': ('planted', 'SMALLINT', ['contract_tree_information']),
                'Planting Obligation': ('planting_obligation', 'TEXT', ['contract_tree_information']),
                'Contract Amendment': ('contract_amendment', 'TEXT', ['contract_tree_information']),
                'USA Allocation %': ('usa_allocation_pct', 'DECIMAL', ['contract_allocation']),
                'USA trees/Allocation/Contracted': ('usa_trees_contracted', 'SMALLINT', ['contract_allocation']),
                'USA trees/Allocation/Planted': ('usa_trees_planted', 'SMALLINT', ['contract_allocation']),
                'Canada Allocation %': ('canada_allocation_pct', 'DECIMAL', ['contract_allocation']),
                "Canada Allocation-tree #'s": ('canada_trees_contracted', 'SMALLINT', ['contract_allocation']),
                'Canada Allocation2017 %': ('canada_2017_allocation_pct', 'DECIMAL', ['contract_allocation']),
                'Can trees/Allocation 2017': ('canada_2017_trees', 'SMALLINT', ['contract_allocation']),
                'Total Can Allocation': ('total_can_allocation', 'SMALLINT', ['contract_allocation']),
                'Survival% as of 12/31/23': ('survival_pct_2023', 'DECIMAL', None),
                '#Trees as of 12/31/23': ('trees_2023', 'SMALLINT', None),
                'Trees as of 12/31/23-US allocation': ('trees_2023_usa', 'SMALLINT', None),
                '#Trees as of 12/31/24-master': ('trees_2024_master', 'SMALLINT', None),
                '2024 Inventory Survival%-master': ('survival_master_2024', 'DECIMAL', None),
                '2024 Estimated Survival%': ('survival_est_2024', 'DECIMAL', None),
                '2024 Survival% Inventory + Estimate': ('survival_combined_2024', 'DECIMAL', None),
                '2024 #Trees Inventory + Estimate': ('trees_combined_2024', 'SMALLINT', None),
                '#Trees as of 2024/estimate -US allocation': ('trees_2024_est_usa', 'SMALLINT', None),
                '#Trees as of 2024/estimate-Can allocation': ('trees_2024_est_can', 'SMALLINT', None),
                '#Trees as of 2024/estimate-Can allocation 2017': ('trees_2024_est_can2017', 'SMALLINT', None),
                'AL+AM': ('al_am', 'SMALLINT', None), 'Species': ('species', 'TEXT', ['contract_tree_information']),
                'Strain': ('strain', 'TEXT', ['contract_tree_information']),
                '% of Contract Replaced': ('pct_replaced', 'DECIMAL', ['contract_replacements']),
                '#Total Replacements': ('total_replacements', 'SMALLINT', ['contract_replacements']),
                '#Replace 25': ('replace_25', 'SMALLINT', ['contract_replacements']),
                '#Replace 24': ('replace_24', 'SMALLINT', ['contract_replacements']),
                '#Replace 23': ('replace_23', 'SMALLINT', ['contract_replacements']),
                '#Replace 22': ('replace_22', 'SMALLINT', ['contract_replacements']),
                '#Replace 21': ('replace_21', 'SMALLINT', ['contract_replacements']),
                '#Replace 20': ('replace_20', 'SMALLINT', ['contract_replacements']),
                '#Replace 19': ('replace_19', 'SMALLINT', ['contract_replacements']),
                '#Replace 18': ('replace_18', 'SMALLINT', ['contract_replacements']),
                '#Replace 17': ('replace_17', 'SMALLINT', ['contract_replacements']),
                '#Replace 16': ('replace_16', 'SMALLINT', ['contract_replacements']),
                'ETP#s': ('etp_numbers', 'SMALLINT', None), 'Audit#s': ('audit_numbers', 'SMALLINT', None),
                'Year of Inventory': ('year_inventory', 'SMALLINT', None),
                'Average THT (Feet)': ('avg_tht_ft', 'SMALLINT', None),
                'Average MHT (Feet)': ('avg_merch_ft', 'SMALLINT', None),
                'MHT % of Target': ('mht_pct_target', 'DECIMAL', None),
                'Average DBH (inches)': ('avg_dbh_in', 'SMALLINT', None),
                'DBH % of Target': ('dbh_pct_target', 'DECIMAL', None), 'Average BF': ('avg_bf', 'DECIMAL', None),
                'Total BF': ('total_bf', 'DECIMAL', None),
                'Projected DBH (Extrapolated Growth/Year)': ('proj_dbh', 'DECIMAL', None),
                'Projected Average BF': ('proj_avg_bf', 'DECIMAL', None),
                'Projected Total BF': ('proj_total_bf', 'DECIMAL', None),
                'ETP Offering Expected BF': ('etp_expected_bf', 'DECIMAL', None),
                'BF Deviation from Expected': ('bf_dev_expected', 'DECIMAL', None),
                'Annual DBH Growth Required to Hit Target': ('annual_dbh_growth_req', 'DECIMAL', None)}
