# Definición de campos y tipos según Contract Database
field_schema = {
    'Contract Code': ('contract_code', 'TEXT'),
    'ETP Year': ('etp_year', 'SMALLINT'),
    'Planting Year': ('planting_year', 'SMALLINT'),
    'Harvest Year (10 year)': ('harvest_year', 'SMALLINT'),
    'Representative': ('representative', 'TEXT'),
    'Farmer#': ('farmer_number', 'TEXT'),
    'Contract Name': ('contract_name', 'TEXT'),
    'Phone': ('phone', 'TEXT'),
    'Status': ('status', 'TEXT'),
    'Email': ('email', 'TEXT'),
    'Address': ('address', 'TEXT'),
    'Shipping Address': ('shipping_address', 'TEXT'),
    'Region': ('region', 'TEXT'),
    'Land Location (GPS)': ('land_location', 'TEXT'),
    'Latitude': ('latitude', 'DOUBLE PRECISION'),
    'Longitude': ('longitude', 'DOUBLE PRECISION'),
    'Column1': ('column1', 'TEXT'),
    'Column2': ('column2', 'TEXT'),
    'Column3': ('column3', 'TEXT'),
    '#TreesContract': ('trees_contract', 'SMALLINT'),
    '#Planted': ('planted', 'SMALLINT'),
    'Planting Obligation': ('planting_obligation', 'TEXT'),
    'Contract Amendment': ('contract_amendment', 'TEXT'),
    'USA Allocation %': ('usa_allocation_pct', 'DECIMAL'),
    'USA trees/Allocation/Contracted': ('usa_trees_contracted', 'SMALLINT'),
    'USA trees/Allocation/Planted': ('usa_trees_planted', 'SMALLINT'),
    'Canada Allocation %': ('canada_allocation_pct', 'DECIMAL'),
    'Canada Allocation-tree #\'s': ('canada_trees_contracted', 'SMALLINT'),
    'Canada Allocation2017 %': ('canada_2017_allocation_pct', 'DECIMAL'),
    'Can trees/Allocation 2017': ('canada_2017_trees', 'SMALLINT'),
    'Total Can Allocation': ('total_can_allocation', 'SMALLINT'),
    'Survival% as of 12/31/23': ('survival_pct_2023', 'DECIMAL'),
    '#Trees as of 12/31/23': ('trees_2023', 'SMALLINT'),
    'Trees as of 12/31/23-US allocation': ('trees_2023_usa', 'SMALLINT'),
    '#Trees as of 12/31/24-master': ('trees_2024_master', 'SMALLINT'),
    '2024 Inventory Survival%-master': ('survival_master_2024', 'DECIMAL'),
    '2024 Estimated Survival%': ('survival_est_2024', 'DECIMAL'),
    '2024 Survival% Inventory + Estimate': ('survival_combined_2024', 'DECIMAL'),
    '2024 #Trees Inventory + Estimate': ('trees_combined_2024', 'SMALLINT'),
    '#Trees as of 2024/estimate -US allocation': ('trees_2024_est_usa', 'SMALLINT'),
    '#Trees as of 2024/estimate-Can allocation': ('trees_2024_est_can', 'SMALLINT'),
    '#Trees as of 2024/estimate-Can allocation 2017': ('trees_2024_est_can2017', 'SMALLINT'),
    'AL+AM': ('al_am', 'SMALLINT'),
    'Species': ('species', 'TEXT'),
    'Strain': ('strain', 'TEXT'),
    '% of Contract Replaced': ('pct_replaced', 'DECIMAL'),
    '#Total Replacements': ('total_replacements', 'SMALLINT'),
    '#Replace 25': ('replace_25', 'SMALLINT'),
    '#Replace 24': ('replace_24', 'SMALLINT'),
    '#Replace 23': ('replace_23', 'SMALLINT'),
    '#Replace 22': ('replace_22', 'SMALLINT'),
    '#Replace 21': ('replace_21', 'SMALLINT'),
    '#Replace 20': ('replace_20', 'SMALLINT'),
    '#Replace 19': ('replace_19', 'SMALLINT'),
    '#Replace 18': ('replace_18', 'SMALLINT'),
    '#Replace 17': ('replace_17', 'SMALLINT'),
    '#Replace 16': ('replace_16', 'SMALLINT'),
    'ETP#s': ('etp_numbers', 'SMALLINT'),
    'Audit#s': ('audit_numbers', 'SMALLINT'),
    'Year of Inventory': ('year_inventory', 'SMALLINT'),
    'Average THT (Feet)': ('avg_tht_ft', 'SMALLINT'),
    'Average MHT (Feet)': ('avg_merch_ft', 'SMALLINT'),
    'MHT % of Target': ('mht_pct_target', 'DECIMAL'),
    'Average DBH (inches)': ('avg_dbh_in', 'SMALLINT'),
    'DBH % of Target': ('dbh_pct_target', 'DECIMAL'),
    'Average BF': ('avg_bf', 'DECIMAL'),
    'Total BF': ('total_bf', 'DECIMAL'),
    'Projected DBH (Extrapolated Growth/Year)': ('proj_dbh', 'DECIMAL'),
    'Projected Average BF': ('proj_avg_bf', 'DECIMAL'),
    'Projected Total BF': ('proj_total_bf', 'DECIMAL'),
    'ETP Offering Expected BF': ('etp_expected_bf', 'DECIMAL'),
    'BF Deviation from Expected': ('bf_dev_expected', 'DECIMAL'),
    'Annual DBH Growth Required to Hit Target': ('annual_dbh_growth_req', 'DECIMAL')
}